# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5817b18c96aeea56ea2f742fa1ad16570ba2460591b980b067117a7fb2f9e30f15d90d50062503d2421cf5b51219d9165f6dbaa377aaf7da4ffa8a650d5c988f

test:
  secret_key_base: 4ebba7691772ab9b55504535031c45d047c78d9286e6f902bb98f683b0c46ebcb69578232117cbb682d110f424bd29a918cd61b20fdcaf54f5d937a1ee0154e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
